from enum import Enum


class GetRecentUserEventsEventTypeItem(str, Enum):
    ADD_MATERIAL_TO_COLLECTION = "ADD_MATERIAL_TO_COLLECTION"
    ARCHIVE_MATERIAL = "ARCHIVE_MATERIAL"
    CHANGE_MATERIAL_CONTENT = "CHANGE_MATERIAL_CONTENT"
    CHANGE_MATERIAL_OWNER = "CHANGE_MATERIAL_OWNER"
    COMMENT_MATERIAL = "COMMENT_MATERIAL"
    COPY_MATERIAL = "COPY_MATERIAL"
    CREATE_MATERIAL = "CREATE_MATERIAL"
    DELETE_MATERIAL = "DELETE_MATERIAL"
    DOWNLOAD_MATERIAL = "DOWNLOAD_MATERIAL"
    EDIT_MATERIAL = "EDIT_MATERIAL"
    EDIT_MATERIAL_RELATION = "EDIT_MATERIAL_RELATION"
    FEEDBACK_MATERIAL = "FEEDBACK_MATERIAL"
    FORK_MATERIAL = "FORK_MATERIAL"
    LINK_SHARE_MATERIAL = "LINK_SHARE_MATERIAL"
    LINK_UNSHARE_MATERIAL = "LINK_UNSHARE_MATERIAL"
    MOVE_MATERIAL = "MOVE_MATERIAL"
    OPEN_EXTERNAL_LINK = "OPEN_EXTERNAL_LINK"
    PROPOSE_MATERIAL_TO_COLLECTION = "PROPOSE_MATERIAL_TO_COLLECTION"
    RATE_MATERIAL = "RATE_MATERIAL"
    REPORT_MATERIAL = "REPORT_MATERIAL"
    REVERT_MATERIAL_VERSION = "REVERT_MATERIAL_VERSION"
    UNRATE_MATERIAL = "UNRATE_MATERIAL"
    VIEW_COLLECTION = "VIEW_COLLECTION"
    VIEW_MATERIAL = "VIEW_MATERIAL"
    VIEW_MATERIAL_EMBEDDED = "VIEW_MATERIAL_EMBEDDED"
    VIEW_MATERIAL_GDPR_CONFIRMED = "VIEW_MATERIAL_GDPR_CONFIRMED"
    VIEW_MATERIAL_PLAY_MEDIA = "VIEW_MATERIAL_PLAY_MEDIA"
    WORKFLOW_CHANGED_ON_MATERIAL = "WORKFLOW_CHANGED_ON_MATERIAL"

    def __str__(self) -> str:
        return str(self.value)
